service: leap-peeper

custom:
  serverless-offline:
    port: 3001

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
       - sdb:GetAttributes
       - sdb:PutAttributes
      Resource: "arn:aws:sdb:*:*:domain/leap_peeper"

functions:
  peeper:
    handler: src/index.handler
    environment:
      SLACK_HOOK: ${env:SLACK_HOOK}
      SLACK_CHANNEL: ${env:SLACK_CHANNEL}
      NODE_URL: ${env:NODE_URL}
      ENV: ${opt:stage}
    events:
      - schedule: rate(1 minute)
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline